FROM node:20.16.0-bookworm-slim AS build

WORKDIR /app

COPY --chown=node:node package.json .

RUN npm install

ENV PATH /app/node_modules/.bin:$PATH

COPY --chown=node:node . .

CMD [ "npm", "run", "dev" ]