services:
  database:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./env/.env.db
    volumes:
      - my-db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 3s
      retries: 5
      start_period: 30s
  
  backend:
    image: harisheoran/backend_img:master
    ports:
      - "6000:6000"
    env_file:
      - ./env/.env
    depends_on:
      - database

  frontend:
    image: harisheoran/frontend_img:master
    ports:
      - "3000:3000"
    env_file:
      - ./env-front/.env

volumes:
  my-db: