services:
  database:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env.db
    volumes:
      - my-db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 3s
      retries: 5
      start_period: 30s
    networks:
      - backend-web
  
  backend:
    image: backend_img:latest
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend-web
      - frontend-web

  frontend:
    image: front_img_dev:latest
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    networks:
      - frontend-web

volumes:
  my-db:

networks:
  frontend-web:
    driver: bridge
  backend-web:
    driver: bridge